"""add extra JSON catch-all and project code detail fields

Revision ID: 0cf63641fbf2
Revises: 7c4b08b24a7b
Create Date: 2026-07-03 05:58:57.869607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf63641fbf2'
down_revision: Union[str, Sequence[str], None] = '7c4b08b24a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('extra', sa.JSON(), nullable=True))
    op.add_column('campaigns', sa.Column('extra', sa.JSON(), nullable=True))
    op.add_column('contacts', sa.Column('extra', sa.JSON(), nullable=True))
    op.add_column('contracts', sa.Column('extra', sa.JSON(), nullable=True))
    op.add_column('deliverables', sa.Column('extra', sa.JSON(), nullable=True))
    op.add_column('employees', sa.Column('extra', sa.JSON(), nullable=True))
    op.add_column('equipment', sa.Column('extra', sa.JSON(), nullable=True))
    op.add_column('expenses', sa.Column('extra', sa.JSON(), nullable=True))
    op.add_column('kp_forgalmak', sa.Column('extra', sa.JSON(), nullable=True))
    op.add_column('project_codes', sa.Column('megjegyzes', sa.Text(), nullable=True))
    op.add_column('project_codes', sa.Column('teljesites_datuma', sa.Date(), nullable=True))
    op.add_column('project_codes', sa.Column('utalas_datuma', sa.Date(), nullable=True))
    op.add_column('project_codes', sa.Column('szamla_url', sa.String(length=500), nullable=True))
    op.add_column('project_codes', sa.Column('tig_alairva_url', sa.String(length=500), nullable=True))
    op.add_column('project_codes', sa.Column('extra', sa.JSON(), nullable=True, comment='a Notionban meglévő, de nálunk saját oszlopot nem kapott mezők nyers értéke'))
    op.add_column('projects', sa.Column('extra', sa.JSON(), nullable=True))
    op.add_column('revenues', sa.Column('extra', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('leiras', sa.String(length=2000), nullable=True))
    op.add_column('tasks', sa.Column('extra', sa.JSON(), nullable=True))
    op.add_column('timesheets', sa.Column('extra', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timesheets', 'extra')
    op.drop_column('tasks', 'extra')
    op.drop_column('tasks', 'leiras')
    op.drop_column('revenues', 'extra')
    op.drop_column('projects', 'extra')
    op.drop_column('project_codes', 'extra')
    op.drop_column('project_codes', 'tig_alairva_url')
    op.drop_column('project_codes', 'szamla_url')
    op.drop_column('project_codes', 'utalas_datuma')
    op.drop_column('project_codes', 'teljesites_datuma')
    op.drop_column('project_codes', 'megjegyzes')
    op.drop_column('kp_forgalmak', 'extra')
    op.drop_column('expenses', 'extra')
    op.drop_column('equipment', 'extra')
    op.drop_column('employees', 'extra')
    op.drop_column('deliverables', 'extra')
    op.drop_column('contracts', 'extra')
    op.drop_column('contacts', 'extra')
    op.drop_column('campaigns', 'extra')
    op.drop_column('assignments', 'extra')
    # ### end Alembic commands ###
