"""batch 1: every notion field for contact, employee, rate

Revision ID: 0e98e74fafbd
Revises: c38bf90881bb
Create Date: 2026-07-03 06:37:52.984720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e98e74fafbd'
down_revision: Union[str, Sequence[str], None] = 'c38bf90881bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('keresztnev_notion', sa.String(length=120), nullable=True, comment='Keresztnév (formula)'))
    op.add_column('contacts', sa.Column('vezeteknev_notion', sa.String(length=120), nullable=True, comment='Vezeték név (formula)'))
    op.add_column('contacts', sa.Column('torolt_anyagok_notion_ids', sa.JSON(), nullable=True, comment='Törölt anyagok (relation)'))
    op.add_column('contacts', sa.Column('kreativ_team_database_notion_ids', sa.JSON(), nullable=True, comment='Kreatív team database (relation)'))
    op.drop_column('contacts', 'extra')
    op.add_column('employees', sa.Column('technikai_ismeret', sa.Text(), nullable=True, comment='TECHNIKAI ISMERET'))
    op.add_column('employees', sa.Column('vallalkozas_kepviselo', sa.String(length=255), nullable=True, comment='Vállalkozás képviselő'))
    op.add_column('employees', sa.Column('leltar_notion_ids', sa.JSON(), nullable=True, comment='🎥 Leltár (relation)'))
    op.add_column('employees', sa.Column('hany_visszajelzese_van_notion', sa.JSON(), nullable=True, comment='Hány visszajelzése van'))
    op.add_column('employees', sa.Column('first_name', sa.String(length=120), nullable=True, comment='First name'))
    op.add_column('employees', sa.Column('last_name', sa.String(length=120), nullable=True, comment='Last name'))
    op.add_column('employees', sa.Column('munkanapok_notion', sa.JSON(), nullable=True, comment='Munkanapok'))
    op.add_column('employees', sa.Column('linkedin_profile', sa.String(length=500), nullable=True, comment='LinkedIn Profile'))
    op.add_column('employees', sa.Column('twitter_profile', sa.String(length=500), nullable=True, comment='Twitter Profile'))
    op.add_column('employees', sa.Column('facebook_profile', sa.String(length=500), nullable=True, comment='Facebook Profile'))
    op.add_column('employees', sa.Column('photo_url', sa.String(length=500), nullable=True, comment='Photo'))
    op.add_column('employees', sa.Column('kulsos_tig_notion_ids', sa.JSON(), nullable=True, comment='Külsős TIG (relation)'))
    op.add_column('employees', sa.Column('belsos_tig_notion_ids', sa.JSON(), nullable=True, comment='Belsős TIG (relation)'))
    op.add_column('employees', sa.Column('orabler_notion', sa.String(length=100), nullable=True, comment='Órabér (formula, pillanatkép)'))
    op.add_column('employees', sa.Column('napidij_notion', sa.String(length=100), nullable=True, comment='Napidíj (formula, pillanatkép)'))
    op.add_column('employees', sa.Column('extra_kiadas_megnevezes', sa.String(length=255), nullable=True, comment='Extra kiadás megnevezés'))
    op.add_column('employees', sa.Column('extra_kiadas_osszeg', sa.Numeric(precision=12, scale=2), nullable=True, comment='Extra kiadás összeg'))
    op.add_column('employees', sa.Column('extra_kiadas_datuma', sa.Date(), nullable=True, comment='Extra kiadás dátuma'))
    op.add_column('employees', sa.Column('belsos_havi_tig', sa.Boolean(), nullable=True, comment='Belsős Havi TIG'))
    op.add_column('employees', sa.Column('source', sa.String(length=100), nullable=True, comment='Source'))
    op.add_column('employees', sa.Column('events_involved_count_notion', sa.JSON(), nullable=True, comment='Events involved count (Σ)'))
    op.add_column('employees', sa.Column('netto_osszeg', sa.Numeric(precision=12, scale=2), nullable=True, comment='Nettó összeg'))
    op.add_column('employees', sa.Column('linked_events_notion_ids', sa.JSON(), nullable=True, comment='Linked Events (relation)'))
    op.add_column('employees', sa.Column('leltar_hiany_20240415_notion', sa.JSON(), nullable=True, comment='2024.04.15. leltár hiány'))
    op.add_column('employees', sa.Column('legutolso_napi_dij_megegyezes', sa.String(length=255), nullable=True, comment='LEGUTOLSÓ NAPI DÍJ MEGEGYEZÉS'))
    op.add_column('employees', sa.Column('milyen_suru_hivjuk', sa.String(length=255), nullable=True, comment='MILYEN SŰRŰN HÍVJUK'))
    op.add_column('employees', sa.Column('megbizas_targya', sa.String(length=255), nullable=True, comment='Megbízás tárgya'))
    op.add_column('employees', sa.Column('szallito_notion_ids', sa.JSON(), nullable=True, comment='Szállító (relation)'))
    op.add_column('employees', sa.Column('keltezes_datuma', sa.Date(), nullable=True, comment='Keltezés dátuma'))
    op.add_column('employees', sa.Column('archive_technika_elhagyas_notion_ids', sa.JSON(), nullable=True, comment='Archive technika elhagyás (relation)'))
    op.add_column('employees', sa.Column('nyilvantartasi_szam', sa.String(length=100), nullable=True, comment='Nyilvántartási szám:'))
    op.add_column('employees', sa.Column('vallakozas_szekhely', sa.String(length=500), nullable=True, comment='Vállakozás székhely'))
    op.add_column('employees', sa.Column('van_e_email_cime_notion', sa.JSON(), nullable=True, comment='van e email címe'))
    op.add_column('employees', sa.Column('vallakozas_neve', sa.String(length=255), nullable=True, comment='Vállakozás neve'))
    op.add_column('employees', sa.Column('phone_2', sa.String(length=50), nullable=True, comment='Phone 2'))
    op.add_column('employees', sa.Column('megjegyzes', sa.Text(), nullable=True, comment='MEGJEGYZÉS'))
    op.add_column('employees', sa.Column('honnan_ismerjuk', sa.Text(), nullable=True, comment='HONNAN ISMERJÜK'))
    op.add_column('employees', sa.Column('birthday', sa.Date(), nullable=True, comment='Birthday'))
    op.add_column('employees', sa.Column('kiadas_projektkodja_notion_ids', sa.JSON(), nullable=True, comment='Kiadás projektkódja (relation)'))
    op.add_column('employees', sa.Column('formula_2_notion', sa.JSON(), nullable=True, comment='Formula 2'))
    op.add_column('employees', sa.Column('main_database_notion_ids', sa.JSON(), nullable=True, comment='📅 Main Database (relation)'))
    op.add_column('employees', sa.Column('vallalkozas_adoszama', sa.String(length=50), nullable=True, comment='Vállalkozás adószáma'))
    op.add_column('employees', sa.Column('plusz_afa', sa.String(length=100), nullable=True, comment='Plusz ÁFA'))
    op.drop_column('employees', 'extra')
    op.add_column('rates', sa.Column('fotos_napi_ber', sa.Numeric(precision=12, scale=2), nullable=True, comment='Fotós napi bér'))
    op.add_column('rates', sa.Column('nev', sa.String(length=255), nullable=True, comment='Name'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rates', 'nev')
    op.drop_column('rates', 'fotos_napi_ber')
    op.add_column('employees', sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('employees', 'plusz_afa')
    op.drop_column('employees', 'vallalkozas_adoszama')
    op.drop_column('employees', 'main_database_notion_ids')
    op.drop_column('employees', 'formula_2_notion')
    op.drop_column('employees', 'kiadas_projektkodja_notion_ids')
    op.drop_column('employees', 'birthday')
    op.drop_column('employees', 'honnan_ismerjuk')
    op.drop_column('employees', 'megjegyzes')
    op.drop_column('employees', 'phone_2')
    op.drop_column('employees', 'vallakozas_neve')
    op.drop_column('employees', 'van_e_email_cime_notion')
    op.drop_column('employees', 'vallakozas_szekhely')
    op.drop_column('employees', 'nyilvantartasi_szam')
    op.drop_column('employees', 'archive_technika_elhagyas_notion_ids')
    op.drop_column('employees', 'keltezes_datuma')
    op.drop_column('employees', 'szallito_notion_ids')
    op.drop_column('employees', 'megbizas_targya')
    op.drop_column('employees', 'milyen_suru_hivjuk')
    op.drop_column('employees', 'legutolso_napi_dij_megegyezes')
    op.drop_column('employees', 'leltar_hiany_20240415_notion')
    op.drop_column('employees', 'linked_events_notion_ids')
    op.drop_column('employees', 'netto_osszeg')
    op.drop_column('employees', 'events_involved_count_notion')
    op.drop_column('employees', 'source')
    op.drop_column('employees', 'belsos_havi_tig')
    op.drop_column('employees', 'extra_kiadas_datuma')
    op.drop_column('employees', 'extra_kiadas_osszeg')
    op.drop_column('employees', 'extra_kiadas_megnevezes')
    op.drop_column('employees', 'napidij_notion')
    op.drop_column('employees', 'orabler_notion')
    op.drop_column('employees', 'belsos_tig_notion_ids')
    op.drop_column('employees', 'kulsos_tig_notion_ids')
    op.drop_column('employees', 'photo_url')
    op.drop_column('employees', 'facebook_profile')
    op.drop_column('employees', 'twitter_profile')
    op.drop_column('employees', 'linkedin_profile')
    op.drop_column('employees', 'munkanapok_notion')
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'first_name')
    op.drop_column('employees', 'hany_visszajelzese_van_notion')
    op.drop_column('employees', 'leltar_notion_ids')
    op.drop_column('employees', 'vallalkozas_kepviselo')
    op.drop_column('employees', 'technikai_ismeret')
    op.add_column('contacts', sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('contacts', 'kreativ_team_database_notion_ids')
    op.drop_column('contacts', 'torolt_anyagok_notion_ids')
    op.drop_column('contacts', 'vezeteknev_notion')
    op.drop_column('contacts', 'keresztnev_notion')
    # ### end Alembic commands ###
