"""finance and TIG spec batch: expense payment gate fields, tig invoices, internal tig, revenue invoice status, client contract fields

Revision ID: 29707ee46474
Revises: 8cfcba9a1004
Create Date: 2026-07-24 21:41:45.502221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29707ee46474'
down_revision: Union[str, Sequence[str], None] = '8cfcba9a1004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_performance_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('allapot', sa.String(length=50), nullable=True, comment='Belsős TIG állapot'),
    sa.Column('megjegyzes', sa.String(length=500), nullable=True),
    sa.Column('netto_osszeg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('plusz_afa', sa.Boolean(), nullable=True),
    sa.Column('teljesites_kezdete', sa.Date(), nullable=True),
    sa.Column('teljesites_vege', sa.Date(), nullable=True),
    sa.Column('szamla_url', sa.String(length=500), nullable=True, comment='Feltöltött számla fájl URL-je'),
    sa.Column('szamla_storage_key', sa.String(length=500), nullable=True),
    sa.Column('szamla_kifizetve', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('performance_certificates', sa.Column('szamla_url', sa.String(length=500), nullable=True, comment='Feltöltött számla fájl URL-je'))
    op.add_column('performance_certificates', sa.Column('szamla_storage_key', sa.String(length=500), nullable=True))
    op.add_column('performance_certificates', sa.Column('szamla_kifizetve', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('performance_certificates', sa.Column('expense_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'performance_certificates', 'expenses', ['expense_id'], ['id'])
    op.add_column('revenues', sa.Column('szamla_kiallitva_datuma', sa.Date(), nullable=True, comment='Számla kiállítva dátuma'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revenues', 'szamla_kiallitva_datuma')
    op.drop_constraint(None, 'performance_certificates', type_='foreignkey')
    op.drop_column('performance_certificates', 'expense_id')
    op.drop_column('performance_certificates', 'szamla_kifizetve')
    op.drop_column('performance_certificates', 'szamla_storage_key')
    op.drop_column('performance_certificates', 'szamla_url')
    op.drop_table('internal_performance_certificates')
    # ### end Alembic commands ###
