"""employee email no longer unique

Revision ID: 31c89de491a3
Revises: 26f555cc0ea2
Create Date: 2026-07-25 15:15:33.913327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c89de491a3'
down_revision: Union[str, Sequence[str], None] = '26f555cc0ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employees_email_key'), 'employees', type_='unique')
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.create_unique_constraint(op.f('employees_email_key'), 'employees', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
