"""leltarazas stocktake session es item

Revision ID: 3b3e3443a8a3
Revises: 0af84cf64a3f
Create Date: 2026-07-06 07:15:47.557372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3e3443a8a3'
down_revision: Union[str, Sequence[str], None] = '0af84cf64a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocktake_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_by_employee_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['started_by_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocktake_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('expected_qty', sa.Integer(), nullable=True, comment='Equipment.osszes_mennyiseg pillanatfelvétele a leltár indításakor'),
    sa.Column('counted_qty', sa.Integer(), nullable=True, comment='A leltározás során ténylegesen megszámolt darabszám'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='A leltározás során beállított állapot (lásd Equipment.allapot)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['stocktake_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocktake_items')
    op.drop_table('stocktake_sessions')
    # ### end Alembic commands ###
