"""media portal: portal_folders/portal_videos/portal_images, extended Portal/Payment fields

Revision ID: 4976883a7987
Revises: 717d7af771c6
Create Date: 2026-07-06 20:29:14.151707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4976883a7987'
down_revision: Union[str, Sequence[str], None] = '717d7af771c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_folders_portal_id'), 'portal_folders', ['portal_id'], unique=False)
    op.create_table('portal_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('key', sa.String(length=500), nullable=True, comment='Eredeti kép R2 kulcsa'),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['portal_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_images_portal_id'), 'portal_images', ['portal_id'], unique=False)
    op.create_table('portal_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_key', sa.String(length=500), nullable=True, comment='Eredeti mp4 R2 kulcsa'),
    sa.Column('mp4_url', sa.String(length=500), nullable=True),
    sa.Column('hls_url', sa.String(length=500), nullable=True, comment='.m3u8 master playlist URL'),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('resolution_label', sa.String(length=20), nullable=True),
    sa.Column('aspect_ratio_label', sa.String(length=20), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='uploading/processing/ready/failed'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['portal_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_videos_portal_id'), 'portal_videos', ['portal_id'], unique=False)
    op.add_column('portals', sa.Column('title_override', sa.String(length=255), nullable=True))
    op.add_column('portals', sa.Column('client_name_override', sa.String(length=255), nullable=True))
    op.add_column('portals', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('portals', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    op.add_column('portals', sa.Column('project_date_override', sa.String(length=100), nullable=True))
    # op.add_column az Enum oszlophoz NEM hozza létre automatikusan a Postgres
    # ENUM típust (ez csak op.create_table-nél történik meg magától) - explicit
    # CREATE TYPE kell előbb, különben "type ... does not exist" hibát dobna.
    portal_payment_mode = sa.Enum('contact', 'paid', name='portal_payment_mode')
    portal_payment_mode.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'portals',
        sa.Column('payment_mode', portal_payment_mode, nullable=False, server_default='contact'),
    )
    op.add_column('portals', sa.Column('notion_page_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_portals_notion_page_id'), 'portals', ['notion_page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portals_notion_page_id'), table_name='portals')
    op.drop_column('portals', 'notion_page_id')
    op.drop_column('portals', 'payment_mode')
    sa.Enum(name='portal_payment_mode').drop(op.get_bind(), checkfirst=True)
    op.drop_column('portals', 'project_date_override')
    op.drop_column('portals', 'cover_image_url')
    op.drop_column('portals', 'description')
    op.drop_column('portals', 'client_name_override')
    op.drop_column('portals', 'title_override')
    op.drop_index(op.f('ix_portal_videos_portal_id'), table_name='portal_videos')
    op.drop_table('portal_videos')
    op.drop_index(op.f('ix_portal_images_portal_id'), table_name='portal_images')
    op.drop_table('portal_images')
    op.drop_index(op.f('ix_portal_folders_portal_id'), table_name='portal_folders')
    op.drop_table('portal_folders')
    # ### end Alembic commands ###
