"""Leltar+Stock igenyek merge: drop project_equipment m2m, add forgatas_datuma_vege

Revision ID: 538417471134
Revises: 6cb11122a5a5
Create Date: 2026-07-03 08:40:25.834595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538417471134'
down_revision: Union[str, Sequence[str], None] = '6cb11122a5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_equipment')
    op.add_column('projects', sa.Column('forgatas_datuma_vege', sa.Date(), nullable=True, comment="A Notion 'Date' property end-je - több napos forgatás záró napja, ha van"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'forgatas_datuma_vege')
    op.create_table('project_equipment',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('project_equipment_equipment_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_equipment_project_id_fkey')),
    sa.PrimaryKeyConstraint('project_id', 'equipment_id', name=op.f('project_equipment_pkey'))
    )
    # ### end Alembic commands ###
