"""initial schema - domain entities

Revision ID: 55ae8901b9c5
Revises: 
Create Date: 2026-07-02 14:34:11.531177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ae8901b9c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nev', sa.String(length=255), nullable=False),
    sa.Column('adoszam', sa.String(length=50), nullable=True),
    sa.Column('szekhely', sa.String(length=255), nullable=True),
    sa.Column('nyilvantartasi_szam', sa.String(length=100), nullable=True),
    sa.Column('kepviselo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('tipus', sa.Enum('belsos', 'kulsos', 'vago', 'kreativ', 'stab', name='employee_type'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.Column('jogositvany', sa.String(length=255), nullable=True),
    sa.Column('munkaszerzodes_url', sa.String(length=500), nullable=True),
    sa.Column('ertekeles', sa.Float(), nullable=True),
    sa.Column('elso_munkanap', sa.Date(), nullable=True),
    sa.Column('utolso_munkanap', sa.Date(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'operator', 'vago', 'ugyfel', name='system_role'), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nev', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('kategoria', sa.String(length=100), nullable=True),
    sa.Column('allapot', sa.String(length=50), nullable=True),
    sa.Column('archive_statusz', sa.String(length=50), nullable=True),
    sa.Column('track_mode', sa.Enum('asset', 'stock', name='equipment_track_mode'), nullable=False),
    sa.Column('osszes_mennyiseg', sa.Integer(), nullable=True, comment='csak stock track_mode esetén relevans'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feladat', sa.String(length=500), nullable=False),
    sa.Column('allapot', sa.String(length=50), nullable=True),
    sa.Column('hatarido', sa.Date(), nullable=True),
    sa.Column('kategoria', sa.String(length=100), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_entity_id'), 'timeline_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_entity_type'), 'timeline_events', ['entity_type'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nev', sa.String(length=255), nullable=False),
    sa.Column('kampany_statusza', sa.String(length=50), nullable=True),
    sa.Column('hatarido', sa.Date(), nullable=True),
    sa.Column('intervalluma', sa.String(length=120), nullable=True),
    sa.Column('kesz', sa.Boolean(), nullable=False),
    sa.Column('felelos_employee_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['felelos_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipus', sa.Enum('kereto', 'alvallalkozoi', name='contract_type'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('ceg_neve', sa.String(length=255), nullable=True),
    sa.Column('szekhely', sa.String(length=255), nullable=True),
    sa.Column('adoszam', sa.String(length=50), nullable=True),
    sa.Column('megbizas_targya', sa.String(length=255), nullable=True),
    sa.Column('szerzodes_allapota', sa.String(length=50), nullable=True),
    sa.Column('szerzodes_file_url', sa.String(length=500), nullable=True),
    sa.Column('keltezes', sa.Date(), nullable=True),
    sa.Column('alairva', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('orabler', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('napibler', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tulora', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('plusz_nap', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('havi_alap', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('elso_munkanap', sa.Date(), nullable=True),
    sa.Column('utolso_munkanap', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_employees',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'employee_id')
    )
    op.create_table('project_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projektkod', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('datum', sa.Date(), nullable=True),
    sa.Column('esemeny_allapota', sa.String(length=50), nullable=True),
    sa.Column('penznem', sa.String(length=10), nullable=False),
    sa.Column('arfolyam', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('szerzodes_url', sa.String(length=500), nullable=True),
    sa.Column('tig_statusza', sa.String(length=50), nullable=True),
    sa.Column('szamla_statusza', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_codes_projektkod'), 'project_codes', ['projektkod'], unique=True)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('megnevezes', sa.String(length=255), nullable=False),
    sa.Column('project_code_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('tipus', sa.String(length=50), nullable=True, comment='belsos / kulsos / extra'),
    sa.Column('netto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('brutto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('penznem', sa.String(length=10), nullable=False),
    sa.Column('kifizetes_modja', sa.String(length=50), nullable=True),
    sa.Column('fizetes_hatarideje', sa.Date(), nullable=True),
    sa.Column('kesz', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_code_id'], ['project_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nev', sa.String(length=255), nullable=False),
    sa.Column('project_code_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('forgatas_datuma', sa.Date(), nullable=True),
    sa.Column('helyszin', sa.String(length=255), nullable=True),
    sa.Column('allapot', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['project_code_id'], ['project_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revenues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_code_id', sa.Integer(), nullable=False),
    sa.Column('bevetel_formaja', sa.String(length=50), nullable=True),
    sa.Column('netto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('brutto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('penznem', sa.String(length=10), nullable=False),
    sa.Column('fizetes_hatarideje', sa.Date(), nullable=True),
    sa.Column('fizetes_datuma', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_code_id'], ['project_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False, comment='stock track_mode esetén hány db'),
    sa.Column('aki_kivitte', sa.String(length=255), nullable=True),
    sa.Column('kivitel_datuma', sa.Date(), nullable=True),
    sa.Column('aki_visszahozta', sa.String(length=255), nullable=True),
    sa.Column('visszahozatal_datuma', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('callsheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('diszpo_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('reszvevok', sa.String(length=500), nullable=True),
    sa.Column('tulora', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('datum', sa.Date(), nullable=True),
    sa.Column('statusz', sa.String(length=50), nullable=True, comment='PREPARED / PRE_SENT / FULL_READY / FULL_REPLY / FULL_SENT'),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliverables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projekt_neve', sa.String(length=255), nullable=False),
    sa.Column('project_code_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('vago_employee_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('allapot', sa.String(length=50), nullable=True),
    sa.Column('hatarido', sa.Date(), nullable=True),
    sa.Column('koltseg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('kesz_anyag_url', sa.String(length=500), nullable=True),
    sa.Column('nyersanyag_url', sa.String(length=500), nullable=True),
    sa.Column('anyag_kikuldve', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['project_code_id'], ['project_codes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['vago_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nev', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kp_forgalmak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('forgalom', sa.String(length=50), nullable=True, comment='bevetel / kiadas'),
    sa.Column('osszeg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('penznem', sa.String(length=10), nullable=False),
    sa.Column('legalis', sa.String(length=50), nullable=True),
    sa.Column('kiadas_datuma', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('share_token', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'live', 'archived', name='portal_status'), nullable=False),
    sa.Column('brand', sa.Enum('hype', 'contentbee', name='portal_brand'), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index(op.f('ix_portals_slug'), 'portals', ['slug'], unique=True)
    op.create_table('project_crew',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'employee_id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deliverable_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('forgatta_employee_id', sa.Integer(), nullable=True),
    sa.Column('technikai_helyesseg', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('kreativ_kepivilag', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('nyersanyag_felhasznalhatosaga', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('ertekeles_kuldese', sa.String(length=50), nullable=True),
    sa.Column('visszajelzes_szoveg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ),
    sa.ForeignKeyConstraint(['forgatta_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False, comment='R2/S3 kulcs'),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('resolution_label', sa.String(length=20), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='processing/ready/failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_request_id', sa.String(length=255), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('revenue_id', sa.Integer(), nullable=True),
    sa.Column('osszeg_huf', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mode', sa.Enum('contact', 'paid', name='payment_mode'), nullable=False),
    sa.Column('allapot', sa.String(length=50), nullable=True),
    sa.Column('barion_payment_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['revenue_id'], ['revenues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_request_id')
    )
    op.create_table('timesheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('deliverable_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('koltseg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('statusz', sa.String(length=50), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timesheets')
    op.drop_table('payments')
    op.drop_table('media_items')
    op.drop_table('feedbacks')
    op.drop_table('project_crew')
    op.drop_index(op.f('ix_portals_slug'), table_name='portals')
    op.drop_table('portals')
    op.drop_table('kp_forgalmak')
    op.drop_table('folders')
    op.drop_table('deliverables')
    op.drop_table('callsheets')
    op.drop_table('assignments')
    op.drop_table('revenues')
    op.drop_table('projects')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_project_codes_projektkod'), table_name='project_codes')
    op.drop_table('project_codes')
    op.drop_table('task_employees')
    op.drop_table('rates')
    op.drop_table('contracts')
    op.drop_table('contacts')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_timeline_events_entity_type'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_entity_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_table('tasks')
    op.drop_table('equipment')
    op.drop_table('employees')
    op.drop_table('clients')
    # ### end Alembic commands ###
    # enum types are not auto-dropped by Alembic - drop them explicitly
    for enum_name in (
        'employee_type',
        'system_role',
        'contract_type',
        'equipment_track_mode',
        'portal_status',
        'portal_brand',
        'payment_mode',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
