"""belsos tig monthly redesign

Revision ID: 57da1f388c94
Revises: 29707ee46474
Create Date: 2026-07-24 22:49:01.133045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57da1f388c94'
down_revision: Union[str, Sequence[str], None] = '29707ee46474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ev/honap eleinte nullázhatóként kerül fel, majd a meglévő sorokat (a
    # projektenkénti régi modellből) a létrehozás dátumára backfill-eljük,
    # mielőtt NOT NULL-ra váltanánk - így nem hasal el nem-üres táblán.
    op.add_column('internal_performance_certificates', sa.Column('ev', sa.Integer(), nullable=True, comment='Év, pl. 2026'))
    op.add_column('internal_performance_certificates', sa.Column('honap', sa.Integer(), nullable=True, comment='Hónap, 1-12'))
    op.execute(
        "UPDATE internal_performance_certificates SET ev = EXTRACT(YEAR FROM created_at), "
        "honap = EXTRACT(MONTH FROM created_at) WHERE ev IS NULL"
    )
    op.alter_column('internal_performance_certificates', 'ev', nullable=False)
    op.alter_column('internal_performance_certificates', 'honap', nullable=False)
    op.create_unique_constraint('uq_internal_tig_employee_month', 'internal_performance_certificates', ['employee_id', 'ev', 'honap'])
    op.drop_constraint(op.f('internal_performance_certificates_project_id_fkey'), 'internal_performance_certificates', type_='foreignkey')
    op.drop_column('internal_performance_certificates', 'teljesites_vege')
    op.drop_column('internal_performance_certificates', 'teljesites_kezdete')
    op.drop_column('internal_performance_certificates', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internal_performance_certificates', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('internal_performance_certificates', sa.Column('teljesites_kezdete', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('internal_performance_certificates', sa.Column('teljesites_vege', sa.DATE(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('internal_performance_certificates_project_id_fkey'), 'internal_performance_certificates', 'projects', ['project_id'], ['id'])
    op.drop_constraint('uq_internal_tig_employee_month', 'internal_performance_certificates', type_='unique')
    op.drop_column('internal_performance_certificates', 'honap')
    op.drop_column('internal_performance_certificates', 'ev')
    # ### end Alembic commands ###
