"""portal fizetes szamlazasi adatok

Revision ID: 634f6e438c87
Revises: f9673eac6e77
Create Date: 2026-08-11 06:21:13.462760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634f6e438c87'
down_revision: Union[str, Sequence[str], None] = 'f9673eac6e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('package_code', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('billing_type', sa.String(length=20), nullable=True, comment='individual | company'))
    op.add_column('payments', sa.Column('billing_name', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('billing_zip', sa.String(length=20), nullable=True))
    op.add_column('payments', sa.Column('billing_city', sa.String(length=120), nullable=True))
    op.add_column('payments', sa.Column('billing_address', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('billing_tax_number', sa.String(length=50), nullable=True, comment='Csak cégnél'))
    op.add_column('payments', sa.Column('billing_email', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('invoice_number', sa.String(length=100), nullable=True))
    op.alter_column('payments', 'allapot',
               existing_type=sa.VARCHAR(length=50),
               comment='started | succeeded | failed',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'allapot',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='started | succeeded | failed',
               existing_nullable=True)
    op.drop_column('payments', 'invoice_number')
    op.drop_column('payments', 'billing_email')
    op.drop_column('payments', 'billing_tax_number')
    op.drop_column('payments', 'billing_address')
    op.drop_column('payments', 'billing_city')
    op.drop_column('payments', 'billing_zip')
    op.drop_column('payments', 'billing_name')
    op.drop_column('payments', 'billing_type')
    op.drop_column('payments', 'package_code')
    # ### end Alembic commands ###
