"""project gmail_last_message_id

Revision ID: 717d7af771c6
Revises: 00f76223f3a3
Create Date: 2026-07-06 10:20:02.023443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '717d7af771c6'
down_revision: Union[str, Sequence[str], None] = '00f76223f3a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('gmail_last_message_id', sa.String(length=255), nullable=True, comment="Az utoljára ebben a diszpó-szálban küldött email RFC822 Message-ID-je (nem Gmail thread ID!) - ez kell a következő email 'In-Reply-To'/'References' fejlécéhez, hogy az valóban válaszként (ne külön levélként) fűződjön a szálhoz a címzettek levelezőjében is, nem csak a küldő Gmail-fiókjában."))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'gmail_last_message_id')
    # ### end Alembic commands ###
