"""contract project_id and eseti fields

Revision ID: 79fd22f33301
Revises: f59db19691c2
Create Date: 2026-07-07 05:53:31.803570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79fd22f33301'
down_revision: Union[str, Sequence[str], None] = 'f59db19691c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('netto_osszeg', sa.Numeric(precision=12, scale=2), nullable=True, comment='Nettó összeg'))
    op.add_column('contracts', sa.Column('teljesites_kezdete', sa.Date(), nullable=True, comment='Teljesítés kezdete'))
    op.add_column('contracts', sa.Column('teljesites_vege', sa.Date(), nullable=True, comment='Teljesítés vége'))
    op.add_column('contracts', sa.Column('plusz_afa', sa.String(length=50), nullable=True, comment='Plusz ÁFA'))
    op.create_foreign_key(
        "contracts_project_id_fkey",
        'contracts', 'projects', ['project_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("contracts_project_id_fkey", 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'plusz_afa')
    op.drop_column('contracts', 'teljesites_vege')
    op.drop_column('contracts', 'teljesites_kezdete')
    op.drop_column('contracts', 'netto_osszeg')
    op.drop_column('contracts', 'project_id')
    # ### end Alembic commands ###
