"""add notion import map table

Revision ID: 7c4b08b24a7b
Revises: 55ae8901b9c5
Create Date: 2026-07-02 15:17:37.518599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4b08b24a7b'
down_revision: Union[str, Sequence[str], None] = '55ae8901b9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notion_import_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notion_page_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notion_import_map_entity_type'), 'notion_import_map', ['entity_type'], unique=False)
    op.create_index(op.f('ix_notion_import_map_notion_page_id'), 'notion_import_map', ['notion_page_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notion_import_map_notion_page_id'), table_name='notion_import_map')
    op.drop_index(op.f('ix_notion_import_map_entity_type'), table_name='notion_import_map')
    op.drop_table('notion_import_map')
    # ### end Alembic commands ###
