"""dispo responsibles

Revision ID: 8aa780957e5c
Revises: 31c89de491a3
Create Date: 2026-07-25 15:58:10.094783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa780957e5c'
down_revision: Union[str, Sequence[str], None] = '31c89de491a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispo_responsibles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('oldal', sa.Enum('GYARTAS', 'TECHNIKA', name='dispo_side'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'oldal', name='uq_dispo_responsible_employee_side')
    )
    op.create_index(op.f('ix_dispo_responsibles_employee_id'), 'dispo_responsibles', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispo_responsibles_employee_id'), table_name='dispo_responsibles')
    op.drop_table('dispo_responsibles')
    # ### end Alembic commands ###
