"""add detail_tab_configs table

Revision ID: 8cfcba9a1004
Revises: cf0359c3182d
Create Date: 2026-07-21 10:55:33.171003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cfcba9a1004'
down_revision: Union[str, Sequence[str], None] = 'cf0359c3182d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail_tab_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('tab_key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='lucide-react ikon neve, opcionális'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('field_keys', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'tab_key', name='uq_detail_tab_entity_key')
    )
    op.create_index(op.f('ix_detail_tab_configs_entity_type'), 'detail_tab_configs', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detail_tab_configs_entity_type'), table_name='detail_tab_configs')
    op.drop_table('detail_tab_configs')
    # ### end Alembic commands ###
