"""kulsos tig multi invoice support

Revision ID: 90c71839b097
Revises: 8aa780957e5c
Create Date: 2026-07-25 16:45:31.985018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c71839b097'
down_revision: Union[str, Sequence[str], None] = '8aa780957e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_certificate_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['performance_certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # A már feltöltött számlák átemelése az új táblába, MIELŐTT eldobjuk a régi
    # oszlopokat - éles adat van bennük, nem elég csak sémát váltani. A fájlnév
    # a storage-kulcs utolsó szegmense (a feltöltéskor nem tároltuk külön).
    op.execute(
        """
        INSERT INTO performance_certificate_invoices (certificate_id, filename, storage_key, url)
        SELECT id,
               COALESCE(NULLIF(regexp_replace(COALESCE(szamla_storage_key, szamla_url), '^.*/', ''), ''), 'szamla'),
               COALESCE(szamla_storage_key, ''),
               szamla_url
        FROM performance_certificates
        WHERE szamla_url IS NOT NULL
        """
    )
    op.drop_column('performance_certificates', 'szamla_url')
    op.drop_column('performance_certificates', 'szamla_storage_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_certificates', sa.Column('szamla_storage_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('performance_certificates', sa.Column('szamla_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Feltöltött számla fájl URL-je'))
    # Visszafelé csak EGY számla fér el TIG-enként (ez volt a régi séma
    # korlátja), ezért a legkorábbit tartjuk meg.
    op.execute(
        """
        UPDATE performance_certificates c
        SET szamla_url = i.url, szamla_storage_key = NULLIF(i.storage_key, '')
        FROM (
            SELECT DISTINCT ON (certificate_id) certificate_id, url, storage_key
            FROM performance_certificate_invoices
            ORDER BY certificate_id, created_at, id
        ) i
        WHERE i.certificate_id = c.id
        """
    )
    op.drop_table('performance_certificate_invoices')
    # ### end Alembic commands ###
