"""equipment serial_number nem unique

Revision ID: 97f6c63d7b1d
Revises: 3b3e3443a8a3
Create Date: 2026-07-06 07:42:03.932014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f6c63d7b1d'
down_revision: Union[str, Sequence[str], None] = '3b3e3443a8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('equipment_serial_number_key'), 'equipment', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('equipment_serial_number_key'), 'equipment', ['serial_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
