"""project code: every notion field as its own column

Revision ID: a5710a4ce864
Revises: 0cf63641fbf2
Create Date: 2026-07-03 06:18:47.208691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5710a4ce864'
down_revision: Union[str, Sequence[str], None] = '0cf63641fbf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_codes', sa.Column('teljesites_datum_formazva', sa.String(length=255), nullable=True, comment='Teljesítés dátum formáz'))
    op.add_column('project_codes', sa.Column('netto_osszeg', sa.Numeric(precision=14, scale=2), nullable=True, comment='Nettó összeg'))
    op.add_column('project_codes', sa.Column('megrendelo_szekhelye', sa.String(length=500), nullable=True, comment='Megrendelő  székhelye'))
    op.add_column('project_codes', sa.Column('profit_szazalek_notion', sa.JSON(), nullable=True, comment='Profit százalék'))
    op.add_column('project_codes', sa.Column('geri_projekt', sa.String(length=100), nullable=True, comment='Geri projekt'))
    op.add_column('project_codes', sa.Column('szerzodes_targya', sa.String(length=255), nullable=True, comment='Szerződés tárgya'))
    op.add_column('project_codes', sa.Column('keltezes_datum_formazva', sa.String(length=255), nullable=True, comment='Keltezés dátum formáz'))
    op.add_column('project_codes', sa.Column('gyartasi_koltseg_notion', sa.JSON(), nullable=True, comment='Gyártási költség'))
    op.add_column('project_codes', sa.Column('szerzodes_specialis_eset', sa.Text(), nullable=True, comment='Szerződés speciális eset'))
    op.add_column('project_codes', sa.Column('fizetesi_hatarido', sa.Date(), nullable=True, comment='Fizetési határidő'))
    op.add_column('project_codes', sa.Column('megrendelo_nyilvantartasi_szam', sa.String(length=100), nullable=True, comment='Megrendelő nyilvántartásiszám'))
    op.add_column('project_codes', sa.Column('szerzodes_kuldes', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Szerződés küldés'))
    op.add_column('project_codes', sa.Column('osszes_koltseg_notion', sa.JSON(), nullable=True, comment='Összes költség (Notion pillanatkép - élő érték: @property osszes_koltseg)'))
    op.add_column('project_codes', sa.Column('tig_teljesitesi_ido', sa.String(length=255), nullable=True, comment='TIG teljesítési idő'))
    op.add_column('project_codes', sa.Column('megrendelo_neve', sa.String(length=255), nullable=True, comment='Megrendelő neve'))
    op.add_column('project_codes', sa.Column('osszesen_netto_notion', sa.JSON(), nullable=True, comment='Összesen nettó'))
    op.add_column('project_codes', sa.Column('megrendelo_adoszama', sa.String(length=50), nullable=True, comment='Megrendelő adószáma'))
    op.add_column('project_codes', sa.Column('netto_notion', sa.JSON(), nullable=True, comment='Nettó'))
    op.add_column('project_codes', sa.Column('helyszin', sa.String(length=255), nullable=True, comment='HELYSZÍN'))
    op.add_column('project_codes', sa.Column('datum_megjegyzes', sa.Text(), nullable=True, comment='DÁTUM megjegyzés'))
    op.add_column('project_codes', sa.Column('szerzodes_plusz_afa', sa.String(length=100), nullable=True, comment='Szerződés plus ÁFA'))
    op.add_column('project_codes', sa.Column('tig_projektnev', sa.String(length=255), nullable=True, comment='TIG projektnév'))
    op.add_column('project_codes', sa.Column('specialis_eset', sa.Text(), nullable=True, comment='Speciális eset'))
    op.add_column('project_codes', sa.Column('szerzodes_helye', sa.String(length=100), nullable=True, comment='Szerződés helye'))
    op.add_column('project_codes', sa.Column('szerzodes_netto_osszeg', sa.Numeric(precision=14, scale=2), nullable=True, comment='Szerződés nettó összeg'))
    op.add_column('project_codes', sa.Column('megrendeloi_emailek', sa.Text(), nullable=True, comment='megrendelői emailek'))
    op.add_column('project_codes', sa.Column('brutto_notion', sa.JSON(), nullable=True, comment='Bruttó'))
    op.add_column('project_codes', sa.Column('kulsos_notion_ids', sa.JSON(), nullable=True, comment='Külsős (relation, nyers Notion page ID-k)'))
    op.add_column('project_codes', sa.Column('alvallalkozok_koltsege_notion', sa.JSON(), nullable=True, comment='Alvállalkozók költsége'))
    op.add_column('project_codes', sa.Column('darabolva', sa.JSON(), nullable=True, comment='Darabolva'))
    op.add_column('project_codes', sa.Column('vagasi_koltseg_notion', sa.JSON(), nullable=True, comment='Vágási költség'))
    op.add_column('project_codes', sa.Column('project_nev', sa.String(length=255), nullable=True, comment='PROJECT NÉV'))
    op.add_column('project_codes', sa.Column('szerzodes_statusza', sa.String(length=50), nullable=True, comment='Szerződés státusza'))
    op.add_column('project_codes', sa.Column('plusz_afa', sa.String(length=100), nullable=True, comment='Plusz ÁFA'))
    op.add_column('project_codes', sa.Column('megerte_e', sa.JSON(), nullable=True, comment='Megérte-e'))
    op.add_column('project_codes', sa.Column('megrendelo_kepviseloje', sa.String(length=255), nullable=True, comment='Megrendelő képviselője'))
    op.add_column('project_codes', sa.Column('szerzodes_projekt_nev', sa.String(length=255), nullable=True, comment='Szerződés projekt név'))
    op.add_column('project_codes', sa.Column('teljesites', sa.Text(), nullable=True, comment='Teljesítés'))
    op.add_column('project_codes', sa.Column('tig_kikuldve', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='TIG kiküldve'))
    op.add_column('project_codes', sa.Column('adminisztracios_tablaban', sa.String(length=100), nullable=True, comment='ADMINISZTRÁCIÓS TÁBLÁBAN?'))
    op.add_column('project_codes', sa.Column('tig_specialis', sa.Text(), nullable=True, comment='TIG Speciális'))
    op.add_column('project_codes', sa.Column('keltezes_datuma', sa.Date(), nullable=True, comment='Keltezés dátuma'))
    op.add_column('project_codes', sa.Column('lejart_notion', sa.JSON(), nullable=True, comment='Lejárt'))
    op.add_column('project_codes', sa.Column('megbizas_targya', sa.String(length=255), nullable=True, comment='Megbízás tárgya'))
    op.add_column('project_codes', sa.Column('belsos_koltseg_akkor', sa.Numeric(precision=14, scale=2), nullable=True, comment='Belsős költség akkor'))
    op.add_column('project_codes', sa.Column('vallalasi_ar_notion', sa.JSON(), nullable=True, comment='Vállalási ár'))
    op.add_column('project_codes', sa.Column('tovabbi_dokumentumok', sa.JSON(), nullable=True, comment='További dokumentumok (files)'))
    op.add_column('project_codes', sa.Column('utomunkak_notion', sa.JSON(), nullable=True, comment='Utómunkák (formula szöveg)'))
    op.add_column('project_codes', sa.Column('bevetel_formaja', sa.String(length=100), nullable=True, comment='Bevétel formája'))
    op.add_column('project_codes', sa.Column('darabolas_notion_ids', sa.JSON(), nullable=True, comment='HYPE ADMIN PROJEKTKÓDOK DARABOLÁS (relation, nyers Notion page ID-k)'))
    op.add_column('project_codes', sa.Column('megrendelo_email', sa.String(length=255), nullable=True, comment='Megrendelő email'))
    op.add_column('project_codes', sa.Column('forintban_notion', sa.JSON(), nullable=True, comment='Forintban'))
    op.add_column('project_codes', sa.Column('szerzodes_keltezes_datuma', sa.Date(), nullable=True, comment='Szerződés keltezés dátuma'))
    op.add_column('project_codes', sa.Column('belsos_koltseg_notion', sa.JSON(), nullable=True, comment='Belsős költség'))
    op.add_column('project_codes', sa.Column('belso_plusz_koltseg_notion', sa.JSON(), nullable=True, comment='Belső plusz költség'))
    op.add_column('project_codes', sa.Column('tig_url', sa.String(length=500), nullable=True, comment='TIG url'))
    op.drop_column('project_codes', 'extra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_codes', sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='a Notionban meglévő, de nálunk saját oszlopot nem kapott mezők nyers értéke'))
    op.drop_column('project_codes', 'tig_url')
    op.drop_column('project_codes', 'belso_plusz_koltseg_notion')
    op.drop_column('project_codes', 'belsos_koltseg_notion')
    op.drop_column('project_codes', 'szerzodes_keltezes_datuma')
    op.drop_column('project_codes', 'forintban_notion')
    op.drop_column('project_codes', 'megrendelo_email')
    op.drop_column('project_codes', 'darabolas_notion_ids')
    op.drop_column('project_codes', 'bevetel_formaja')
    op.drop_column('project_codes', 'utomunkak_notion')
    op.drop_column('project_codes', 'tovabbi_dokumentumok')
    op.drop_column('project_codes', 'vallalasi_ar_notion')
    op.drop_column('project_codes', 'belsos_koltseg_akkor')
    op.drop_column('project_codes', 'megbizas_targya')
    op.drop_column('project_codes', 'lejart_notion')
    op.drop_column('project_codes', 'keltezes_datuma')
    op.drop_column('project_codes', 'tig_specialis')
    op.drop_column('project_codes', 'adminisztracios_tablaban')
    op.drop_column('project_codes', 'tig_kikuldve')
    op.drop_column('project_codes', 'teljesites')
    op.drop_column('project_codes', 'szerzodes_projekt_nev')
    op.drop_column('project_codes', 'megrendelo_kepviseloje')
    op.drop_column('project_codes', 'megerte_e')
    op.drop_column('project_codes', 'plusz_afa')
    op.drop_column('project_codes', 'szerzodes_statusza')
    op.drop_column('project_codes', 'project_nev')
    op.drop_column('project_codes', 'vagasi_koltseg_notion')
    op.drop_column('project_codes', 'darabolva')
    op.drop_column('project_codes', 'alvallalkozok_koltsege_notion')
    op.drop_column('project_codes', 'kulsos_notion_ids')
    op.drop_column('project_codes', 'brutto_notion')
    op.drop_column('project_codes', 'megrendeloi_emailek')
    op.drop_column('project_codes', 'szerzodes_netto_osszeg')
    op.drop_column('project_codes', 'szerzodes_helye')
    op.drop_column('project_codes', 'specialis_eset')
    op.drop_column('project_codes', 'tig_projektnev')
    op.drop_column('project_codes', 'szerzodes_plusz_afa')
    op.drop_column('project_codes', 'datum_megjegyzes')
    op.drop_column('project_codes', 'helyszin')
    op.drop_column('project_codes', 'netto_notion')
    op.drop_column('project_codes', 'megrendelo_adoszama')
    op.drop_column('project_codes', 'osszesen_netto_notion')
    op.drop_column('project_codes', 'megrendelo_neve')
    op.drop_column('project_codes', 'tig_teljesitesi_ido')
    op.drop_column('project_codes', 'osszes_koltseg_notion')
    op.drop_column('project_codes', 'szerzodes_kuldes')
    op.drop_column('project_codes', 'megrendelo_nyilvantartasi_szam')
    op.drop_column('project_codes', 'fizetesi_hatarido')
    op.drop_column('project_codes', 'szerzodes_specialis_eset')
    op.drop_column('project_codes', 'gyartasi_koltseg_notion')
    op.drop_column('project_codes', 'keltezes_datum_formazva')
    op.drop_column('project_codes', 'szerzodes_targya')
    op.drop_column('project_codes', 'geri_projekt')
    op.drop_column('project_codes', 'profit_szazalek_notion')
    op.drop_column('project_codes', 'megrendelo_szekhelye')
    op.drop_column('project_codes', 'netto_osszeg')
    op.drop_column('project_codes', 'teljesites_datum_formazva')
    # ### end Alembic commands ###
