"""performance certificate tig table

Revision ID: af8bf2e54eba
Revises: df976f6b6eff
Create Date: 2026-07-09 13:28:49.293774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8bf2e54eba'
down_revision: Union[str, Sequence[str], None] = 'df976f6b6eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('allapot', sa.String(length=50), nullable=True, comment='TIG állapot'),
    sa.Column('file_url', sa.String(length=500), nullable=True, comment='Generált TIG Google Docs linkje'),
    sa.Column('ceg_neve', sa.String(length=255), nullable=True),
    sa.Column('szekhely', sa.String(length=255), nullable=True),
    sa.Column('adoszam', sa.String(length=50), nullable=True),
    sa.Column('megbizas_targya', sa.String(length=255), nullable=True),
    sa.Column('netto_osszeg', sa.Numeric(precision=12, scale=2), nullable=True, comment='Nettó TIG'),
    sa.Column('plusz_afa', sa.Boolean(), nullable=True),
    sa.Column('teljesites_kezdete', sa.Date(), nullable=True),
    sa.Column('teljesites_vege', sa.Date(), nullable=True),
    sa.Column('keltezes', sa.Date(), nullable=True, comment='Keltezési idő'),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_certificates')
    # ### end Alembic commands ###
