"""Belsos idoszakok: mettol meddig volt belsos

Revision ID: bf20f2bb43e7
Revises: 5daf5db7a92a
Create Date: 2026-08-08 06:52:55.758581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf20f2bb43e7'
down_revision: Union[str, Sequence[str], None] = '5daf5db7a92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('belsos_idoszakok',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('kezdet', sa.Date(), nullable=True),
    sa.Column('veg', sa.Date(), nullable=True),
    sa.Column('megjegyzes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_belsos_idoszakok_employee_id'), 'belsos_idoszakok', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_belsos_idoszakok_employee_id'), table_name='belsos_idoszakok')
    op.drop_table('belsos_idoszakok')
    # ### end Alembic commands ###
