"""per-employee page access es field visibility

Revision ID: c4ad3235bc66
Revises: e4f1808ac9b2
Create Date: 2026-07-04 06:47:16.372982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ad3235bc66'
down_revision: Union[str, Sequence[str], None] = 'e4f1808ac9b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_access_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('allowed_pages', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    # A field_visibility_configs eddig globális (nem munkatárs-specifikus) sorai
    # nem feleltethetők meg egyetlen employee_id-nak sem - ez csak beállítás-
    # preferencia adat, nem üzleti adat, biztonságosan törölhető/újra
    # beállítható a funkció egyénenkénti átalakítása után.
    op.execute("DELETE FROM field_visibility_configs")
    op.add_column('field_visibility_configs', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('field_visibility_configs_entity_type_key'), 'field_visibility_configs', type_='unique')
    op.create_unique_constraint('uq_field_visibility_employee_entity', 'field_visibility_configs', ['employee_id', 'entity_type'])
    op.create_foreign_key(
        'field_visibility_configs_employee_id_fkey', 'field_visibility_configs', 'employees', ['employee_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('field_visibility_configs_employee_id_fkey', 'field_visibility_configs', type_='foreignkey')
    op.drop_constraint('uq_field_visibility_employee_entity', 'field_visibility_configs', type_='unique')
    op.create_unique_constraint(op.f('field_visibility_configs_entity_type_key'), 'field_visibility_configs', ['entity_type'], postgresql_nulls_not_distinct=False)
    op.drop_column('field_visibility_configs', 'employee_id')
    op.drop_table('page_access_configs')
    # ### end Alembic commands ###
