"""google calendar sync

Revision ID: c503a4a89311
Revises: cb73bf7fb67f
Create Date: 2026-07-25 12:36:35.117294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c503a4a89311'
down_revision: Union[str, Sequence[str], None] = 'cb73bf7fb67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('sync_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_sync_state_calendar_id'), 'calendar_sync_state', ['calendar_id'], unique=True)
    op.add_column('projects', sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True, comment='A HYPE CALENDAR naptárból szinkronizált esemény Google Calendar event ID-je - csak a naptárból automatikusan létrehozott projekteknek van (lásd services/google_calendar.py).'))
    op.create_index(op.f('ix_projects_google_calendar_event_id'), 'projects', ['google_calendar_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_google_calendar_event_id'), table_name='projects')
    op.drop_column('projects', 'google_calendar_event_id')
    op.drop_index(op.f('ix_calendar_sync_state_calendar_id'), table_name='calendar_sync_state')
    op.drop_table('calendar_sync_state')
    # ### end Alembic commands ###
