"""belsos tig multi invoice support

Revision ID: cb73bf7fb67f
Revises: 57da1f388c94
Create Date: 2026-07-24 22:56:53.017896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb73bf7fb67f'
down_revision: Union[str, Sequence[str], None] = '57da1f388c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_performance_certificate_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['internal_performance_certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('internal_performance_certificates', 'szamla_storage_key')
    op.drop_column('internal_performance_certificates', 'szamla_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internal_performance_certificates', sa.Column('szamla_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Feltöltött számla fájl URL-je'))
    op.add_column('internal_performance_certificates', sa.Column('szamla_storage_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_table('internal_performance_certificate_invoices')
    # ### end Alembic commands ###
