"""portal deliverable_id

Revision ID: cf0359c3182d
Revises: af8bf2e54eba
Create Date: 2026-07-13 12:00:16.729433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0359c3182d'
down_revision: Union[str, Sequence[str], None] = 'af8bf2e54eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portals', sa.Column('deliverable_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'portals', ['deliverable_id'])
    op.create_foreign_key(None, 'portals', 'deliverables', ['deliverable_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portals', type_='foreignkey')
    op.drop_constraint(None, 'portals', type_='unique')
    op.drop_column('portals', 'deliverable_id')
    # ### end Alembic commands ###
