"""Kotelezettsegek, autok es autos kiadasok

Visszatérő kötelezettségek (előfizetés, biztosítás, forgalmi) fordulóval,
fordulónkénti időszakokkal, és céges autók. Az autóra könyvelt kiadás nem új
tábla: az `expenses.auto_id` köti a járműhöz, így ugyanaz a sor szerepel a
Pénzügy összesítő kiadásai közt is.

Revision ID: d4a6f86fce3c
Revises: d7c2e4a91b60
Create Date: 2026-08-08 10:16:36.880853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a6f86fce3c'
down_revision: Union[str, Sequence[str], None] = 'd7c2e4a91b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autok',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rendszam', sa.String(length=20), nullable=False),
    sa.Column('megnevezes', sa.String(length=255), nullable=True, comment='Pl. Ford Transit - gyártásos busz'),
    sa.Column('tipus', sa.String(length=255), nullable=True, comment='Márka és típus'),
    sa.Column('evjarat', sa.Integer(), nullable=True),
    sa.Column('km_ora', sa.Integer(), nullable=True),
    sa.Column('felelos_id', sa.Integer(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('megjegyzes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['felelos_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autok_felelos_id'), 'autok', ['felelos_id'], unique=False)
    op.create_index(op.f('ix_autok_rendszam'), 'autok', ['rendszam'], unique=True)
    op.create_table('kotelezettsegek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nev', sa.String(length=255), nullable=False),
    sa.Column('csomag', sa.String(length=500), nullable=True),
    sa.Column('tipus', sa.String(length=20), nullable=False),
    sa.Column('ciklus', sa.String(length=20), nullable=False),
    sa.Column('fordulo_nap', sa.Integer(), nullable=True, comment='A hónap napja, 1-31'),
    sa.Column('fordulo_honap', sa.Integer(), nullable=True, comment='Éves ciklusnál a hónap, 1-12'),
    sa.Column('kovetkezo_fordulo', sa.Date(), nullable=True, comment='Konkrét következő forduló / lejárat - erősebb a mintánál'),
    sa.Column('kezdet', sa.Date(), nullable=True),
    sa.Column('osztaly', sa.String(length=100), nullable=True),
    sa.Column('felelos_id', sa.Integer(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('auto_id', sa.Integer(), nullable=True),
    sa.Column('ar_osszeg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ar_penznem', sa.String(length=3), nullable=False),
    sa.Column('huf_becsles_honap', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('huf_becsles_ev', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('szamla_forras', sa.Text(), nullable=True),
    sa.Column('kartya', sa.String(length=100), nullable=True),
    sa.Column('megjegyzes', sa.Text(), nullable=True),
    sa.Column('ertesites_napokkal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auto_id'], ['autok.id'], ),
    sa.ForeignKeyConstraint(['felelos_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kotelezettsegek_auto_id'), 'kotelezettsegek', ['auto_id'], unique=False)
    op.create_index(op.f('ix_kotelezettsegek_felelos_id'), 'kotelezettsegek', ['felelos_id'], unique=False)
    op.create_index(op.f('ix_kotelezettsegek_osztaly'), 'kotelezettsegek', ['osztaly'], unique=False)
    op.create_table('kotelezettseg_idoszakok',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kotelezettseg_id', sa.Integer(), nullable=False),
    sa.Column('esedekesseg', sa.Date(), nullable=False),
    sa.Column('osszeg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('penznem', sa.String(length=3), nullable=False),
    sa.Column('huf_osszeg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fizetve', sa.Boolean(), nullable=False),
    sa.Column('megjegyzes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kotelezettseg_id'], ['kotelezettsegek.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kotelezettseg_id', 'esedekesseg', name='uq_kotelezettseg_idoszak_esedekesseg')
    )
    op.create_index(op.f('ix_kotelezettseg_idoszakok_kotelezettseg_id'), 'kotelezettseg_idoszakok', ['kotelezettseg_id'], unique=False)
    op.add_column('expenses', sa.Column('auto_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expenses_auto_id'), 'expenses', ['auto_id'], unique=False)
    op.create_foreign_key('fk_expenses_auto_id', 'expenses', 'autok', ['auto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_expenses_auto_id', 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_auto_id'), table_name='expenses')
    op.drop_column('expenses', 'auto_id')
    op.drop_index(op.f('ix_kotelezettseg_idoszakok_kotelezettseg_id'), table_name='kotelezettseg_idoszakok')
    op.drop_table('kotelezettseg_idoszakok')
    op.drop_index(op.f('ix_kotelezettsegek_osztaly'), table_name='kotelezettsegek')
    op.drop_index(op.f('ix_kotelezettsegek_felelos_id'), table_name='kotelezettsegek')
    op.drop_index(op.f('ix_kotelezettsegek_auto_id'), table_name='kotelezettsegek')
    op.drop_table('kotelezettsegek')
    op.drop_index(op.f('ix_autok_rendszam'), table_name='autok')
    op.drop_index(op.f('ix_autok_felelos_id'), table_name='autok')
    op.drop_table('autok')
    # ### end Alembic commands ###
