"""sajat papir tarhely kulcs TIG-hez es szerzodeshez

Revision ID: dcd3e232823d
Revises: 7d225d5359fd
Create Date: 2026-08-10 09:22:46.599177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd3e232823d'
down_revision: Union[str, Sequence[str], None] = '7d225d5359fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('szerzodes_file_storage_key', sa.String(length=500), nullable=True))
    op.add_column('performance_certificates', sa.Column('file_storage_key', sa.String(length=500), nullable=True))
    op.alter_column('performance_certificates', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               comment='A TIG dokumentum linkje',
               existing_comment='Generált TIG Google Docs linkje',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_certificates', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Generált TIG Google Docs linkje',
               existing_comment='A TIG dokumentum linkje',
               existing_nullable=True)
    op.drop_column('performance_certificates', 'file_storage_key')
    op.drop_column('contracts', 'szerzodes_file_storage_key')
    # ### end Alembic commands ###
