"""post shoot feedback and project utokoveto token

Revision ID: df976f6b6eff
Revises: 268cc84003f1
Create Date: 2026-07-09 13:15:08.473123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df976f6b6eff'
down_revision: Union[str, Sequence[str], None] = '268cc84003f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_shoot_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('erdemleges_tortent', sa.Text(), nullable=True, comment='Történt-e bármi érdemleges a forgatással kapcsolatban'),
    sa.Column('technika_info', sa.Text(), nullable=True, comment='Infó a nálad levő technikával kapcsolatban'),
    sa.Column('egyeb', sa.Text(), nullable=True, comment='Bármi egyéb, amit itt hagynál a diszpódat követően'),
    sa.Column('werk_fotok', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('utokoveto_token', sa.String(length=64), nullable=True))
    op.create_unique_constraint('projects_utokoveto_token_key', 'projects', ['utokoveto_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_utokoveto_token_key', 'projects', type_='unique')
    op.drop_column('projects', 'utokoveto_token')
    op.drop_table('post_shoot_feedbacks')
    # ### end Alembic commands ###
