"""project forgatas idopont

Revision ID: e2c4615df1bb
Revises: 16e6352592d7
Create Date: 2026-07-29 13:30:04.819435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c4615df1bb'
down_revision: Union[str, Sequence[str], None] = '16e6352592d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('forgatas_kezdes_ido', sa.Time(), nullable=True, comment='Forgatás kezdete (óra:perc)'))
    op.add_column('projects', sa.Column('forgatas_veg_ido', sa.Time(), nullable=True, comment='Forgatás vége (óra:perc)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'forgatas_veg_ido')
    op.drop_column('projects', 'forgatas_kezdes_ido')
    # ### end Alembic commands ###
