"""szerzodes keszites es alvallakozo keretszerzodes FK-k a Project-en

Revision ID: e6b110d8eaa2
Revises: 538417471134
Create Date: 2026-07-03 09:05:56.723088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6b110d8eaa2'
down_revision: Union[str, Sequence[str], None] = '538417471134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('szerzodes_pdf_url', sa.String(length=500), nullable=True, comment='Szerződés készítése és küldése gomb - generált szerződés Google Docs linkje'))
    op.add_column('projects', sa.Column('szerzodes_keszites_employee_id', sa.Integer(), nullable=True, comment="'Szerződés készítés' relation (Külsős és belsős) - a kiválasztott ember adatai a megbízott_* mezőkbe másolódnak (lásd app/services/contract_actions.py)"))
    op.add_column('projects', sa.Column('alvallakozo_keretszerzodes_contract_id', sa.Integer(), nullable=True, comment="'Alvállakozó keretszerződés (külsős)' relation - egy meglévő keretszerződés hozzálinkelése ehhez a projekthez"))
    op.alter_column('projects', 'alvallakozo_keretszerzodes_notion_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Alvállakozó keretszerződés (külsős) (relation) - nyers Notion import',
               existing_comment='Alvállakozó keretszerződés (külsős) (relation)',
               existing_nullable=True)
    op.alter_column('projects', 'szerzodes_keszites_notion_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Szerződés készítés (relation) - nyers Notion import',
               existing_comment='Szerződés készítés (relation)',
               existing_nullable=True)
    op.create_foreign_key(
        "projects_alvallakozo_keretszerzodes_contract_id_fkey",
        'projects', 'contracts', ['alvallakozo_keretszerzodes_contract_id'], ['id'],
    )
    op.create_foreign_key(
        "projects_szerzodes_keszites_employee_id_fkey",
        'projects', 'employees', ['szerzodes_keszites_employee_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("projects_alvallakozo_keretszerzodes_contract_id_fkey", 'projects', type_='foreignkey')
    op.drop_constraint("projects_szerzodes_keszites_employee_id_fkey", 'projects', type_='foreignkey')
    op.alter_column('projects', 'szerzodes_keszites_notion_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Szerződés készítés (relation)',
               existing_comment='Szerződés készítés (relation) - nyers Notion import',
               existing_nullable=True)
    op.alter_column('projects', 'alvallakozo_keretszerzodes_notion_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Alvállakozó keretszerződés (külsős) (relation)',
               existing_comment='Alvállakozó keretszerződés (külsős) (relation) - nyers Notion import',
               existing_nullable=True)
    op.drop_column('projects', 'alvallakozo_keretszerzodes_contract_id')
    op.drop_column('projects', 'szerzodes_keszites_employee_id')
    op.drop_column('projects', 'szerzodes_pdf_url')
    # ### end Alembic commands ###
