"""google oauth token storage

Revision ID: f1c5e708f311
Revises: c503a4a89311
Create Date: 2026-07-25 14:12:40.663428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c5e708f311'
down_revision: Union[str, Sequence[str], None] = 'c503a4a89311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('token_json', sa.Text(), nullable=True),
    sa.Column('account_email', sa.String(length=255), nullable=True),
    sa.Column('pending_state', sa.String(length=128), nullable=True),
    sa.Column('pending_state_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_oauth_tokens_key'), 'google_oauth_tokens', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_oauth_tokens_key'), table_name='google_oauth_tokens')
    op.drop_table('google_oauth_tokens')
    # ### end Alembic commands ###
