"""belsos TIG szamlazo cege

Revision ID: f9673eac6e77
Revises: dcd3e232823d
Create Date: 2026-08-10 11:14:23.115010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9673eac6e77'
down_revision: Union[str, Sequence[str], None] = 'dcd3e232823d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internal_performance_certificates', sa.Column('vallalkozas_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_internal_tig_vallalkozas_id', 'internal_performance_certificates', 'vallalkozasok', ['vallalkozas_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_internal_tig_vallalkozas_id', 'internal_performance_certificates', type_='foreignkey')
    op.drop_column('internal_performance_certificates', 'vallalkozas_id')
    # ### end Alembic commands ###
