"""deliverable connections: felvezeto, assigned_to, kontaktok, comments, visszajelzo

Revision ID: fe63036ab80a
Revises: abbe825f27cd
Create Date: 2026-07-04 09:12:26.867383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe63036ab80a'
down_revision: Union[str, Sequence[str], None] = 'abbe825f27cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliverable_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deliverable_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliverable_contacts',
    sa.Column('deliverable_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ),
    sa.PrimaryKeyConstraint('deliverable_id', 'contact_id')
    )
    op.add_column('deliverables', sa.Column('aki_felvezette_employee_id', sa.Integer(), nullable=True))
    op.add_column('deliverables', sa.Column('assigned_to_employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'deliverables_assigned_to_employee_id_fkey', 'deliverables', 'employees', ['assigned_to_employee_id'], ['id']
    )
    op.create_foreign_key(
        'deliverables_aki_felvezette_employee_id_fkey', 'deliverables', 'employees', ['aki_felvezette_employee_id'], ['id']
    )
    op.add_column('feedbacks', sa.Column('visszajelzo_employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'feedbacks_visszajelzo_employee_id_fkey', 'feedbacks', 'employees', ['visszajelzo_employee_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feedbacks_visszajelzo_employee_id_fkey', 'feedbacks', type_='foreignkey')
    op.drop_column('feedbacks', 'visszajelzo_employee_id')
    op.drop_constraint('deliverables_assigned_to_employee_id_fkey', 'deliverables', type_='foreignkey')
    op.drop_constraint('deliverables_aki_felvezette_employee_id_fkey', 'deliverables', type_='foreignkey')
    op.drop_column('deliverables', 'assigned_to_employee_id')
    op.drop_column('deliverables', 'aki_felvezette_employee_id')
    op.drop_table('deliverable_contacts')
    op.drop_table('deliverable_comments')
    # ### end Alembic commands ###
